version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sports-db
    environment:
      POSTGRES_DB: sports_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sports2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sports-network

  redis:
    image: redis:7-alpine
    container_name: sports-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sports-network

volumes:
  postgres_data:
  redis_data:

networks:
  sports-network:
    driver: bridge
